import { useState } from 'react';
import { Sparkles, RefreshCw } from 'lucide-react';
import { getAdvice } from '../../services/weatherService.js';

const AdvisorCard = ({ recordId }) => {
  const [advice, setAdvice] = useState(null);
  const [source, setSource] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleGenerate = async () => {
    if (!recordId) return;
    setLoading(true);
    setError(null);
    try {
      const result = await getAdvice(recordId);
      setAdvice(result.advice);
      setSource(result.source);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-indigo-950 via-indigo-900 to-violet-900 p-6 text-white shadow-panel">
      <div className="absolute inset-0 bg-grid-lines bg-grid opacity-10" />

      <div className="relative flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/10">
            <Sparkles size={16} className="text-violet-300" />
          </div>
          <div>
            <p className="font-display text-sm font-semibold">AI Weather Advisor</p>
            <p className="text-xs text-white/50">Live-conditions recommendation engine</p>
          </div>
        </div>
        {advice && (
          <button
            onClick={handleGenerate}
            aria-label="Regenerate"
            className="flex h-8 w-8 items-center justify-center rounded-full text-white/50 hover:text-white"
          >
            <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
          </button>
        )}
      </div>

      <div className="relative mt-6">
        {!advice && !loading && !error && (
          <div className="flex flex-col items-center py-4 text-center">
            <Sparkles size={40} strokeWidth={1.3} className="mb-3 text-violet-300" />
            <p className="font-display text-base font-semibold">Advice Synthesizer Ready</p>
            <p className="mt-2 max-w-xs text-sm text-white/60">
              Tap below to generate immediate, structured advice about what to wear and what activities suit today's
              conditions.
            </p>
            <button
              onClick={handleGenerate}
              className="mt-5 w-full rounded-full bg-violet-500 py-3 text-sm font-semibold text-white transition hover:bg-violet-400"
            >
              Generate Smart Advice
            </button>
          </div>
        )}

        {loading && (
          <div className="flex flex-col items-center py-6 text-center">
            <Sparkles size={32} className="mb-3 animate-pulse-soft text-violet-300" />
            <p className="text-sm text-white/60">Thinking through today's conditions…</p>
          </div>
        )}

        {error && <p className="text-sm text-coral-400">{error}</p>}

        {advice && !loading && (
          <div>
            <p className="text-sm leading-relaxed text-white/90">{advice}</p>
            {source && (
              <p className="mt-3 text-[10px] uppercase tracking-wide text-white/30">
                {source === 'llm' ? 'Generated by AI' : 'Generated from live conditions'}
              </p>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default AdvisorCard;
